---
- name: Read device information
  extreme_community.xiqse.device_read:
    ip_address: "{{ ip_address }}"
    provider:
      host: "{{ xiqse_host }}"
      client_id: "{{ xiqse_client }}"
      client_secret: "{{ xiqse_secret }}"
      port: "{{ device_hostname_xiqse_port }}"
      protocol: "{{ device_hostname_xiqse_protocol }}"
      verify: "{{ device_hostname_xiqse_verify }}"

- name: Allow time for XIQ-SE to finish synchronizing
  ansible.builtin.wait_for:
    timeout: 10
